var colors = ['white','black','custom'];
colors[2]= 'beige';
var el = document.getElementById('color');
el.textContent = colors[2];
var title;
var message;
title = "Molly's Special Offers";
message ='<a href = \"sale.html\">25% off </a>;
var eltitle = document.getElementById('title');
eltitle.textContent = title;
var elNote =document.getElementById('note');
elNote.innerHTML =message;
var username;
var message;
username = 'Molly';
message = 'See our upcoming range';
var elName = document.getElementById('name');
elName.textContent = username;
var elNote = document.getElementById('note');
elNote.textContent = message;
var greeting = 'Howdy';
var name = 'Molly';
var wellcomeMessage;
